version: '3.8'
services:
    php-apache:
        container_name: php-apache
        build:
            context: .
        ports:
            - ${APACHE_DEFAULT_PORT}:80
        volumes:
            - ./:/var/www/html
            - ./config/vhosts:/etc/apache2/sites-enabled
        links:
            - mariadb
        environment:
            APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    mariadb:
        container_name: database
        image: mariadb:10.6
        restart: 'always'
        ports:
            - "127.0.0.1:${MARIA_DB_PORT}:3306"
        volumes:
            - ./database:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
volumes:
    mariadb:
